name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          
      - name: Get name
        id: name
        run: echo "::set-output name=file_name::fga-eps-mds-2021-2-Oraculo-FrontEnd-$(TZ='America/Sao_Paulo' date +'%m-%d-%Y-%H-%M-%S')-${{github.ref_name}}"

      - name: Run tests
        run: sudo docker-compose run frontend bash -c  "yarn && yarn test --coverage"

      - name: Create JSON
        run: curl -X POST 'https://sonarcloud.io/api/measures/component_tree?component=fga-eps-mds_2021.2-Oraculo-FrontEnd&branch=main&metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,security_rating,tests,test_success_density,test_execution_time,reliability_rating&ps=500' > ${{ steps.name.outputs.file_name }}.json


      - name: Make release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            fga-eps-mds_2021.2-Oraculo-FrontEnd-${{ steps.date.outputs.date }}.json
      - name: Pushes sonar file
        uses: dmnemec/copy_file_to_another_repo_action@80732d64341473fa7165a3b2b6c7b0ee164193f8
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: ${{ steps.name.outputs.file_name }}.json
          destination_repo: "fga-eps-mds/2021-2-Oraculo-Doc"
          destination_branch: "master"
          destination_folder: "analytics-raw-data"
          user_email: ${{ secrets.USER_EMAIL }}
          user_name: ${{ secrets.USER_NAME }}
          commit_message: "Adding SonarCloud file - fga-eps-mds_2021.2-Oraculo-FrontEnd-${{ steps.date.outputs.date }}.json"

     
